//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneContactMvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressType
    {
        public AddressType()
        {
            this.Address = new HashSet<Address>();
        }
    
        public int AddressTypeID { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Address> Address { get; set; }
    }
}
