//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneContactMvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public int PhoneID { get; set; }
        public string Number { get; set; }
        public int PersonID { get; set; }
        public int PhoneTypeID { get; set; }
    
        public virtual Person People { get; set; }
        public virtual PhoneType PhoneTypes { get; set; }
    }
}
